config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dogs
  resources :owners
  get 'pages/index'

  get 'pages/about'

  root 'pages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner
  belongs_to :breed
  
  validates :name, :owner_id, :breed_id, presence: true

  has_attached_file :avatar, 
    :styles => {
      :medium => "300x300>", 
      :thumb => "100x100>" }, 
    :default_url => ":style_missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 3.megabytes, :unless => Proc.new {|m| m[:avatar_file_name].blank?}
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :dogs

  def lastfirst
    "#{last_name}, #{first_name}"   #is defined now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Restrict access to admin module for non-admin users
  def authenticate_admin_user!
    raise SecurityError unless current_user.try(:admin?)
  end

  rescue_from SecurityError do |exception|
    redirect_to root_url, alert: 'You do not have access to that feature.'
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin_user!, except: [:index, :show]

  # GET /dogs
  # GET /dogs.json
  def index
    if params[:search]
      @dogs = Dog.where("name LIKE ?", "%#{params[:search]}%")
      if @dogs.size.zero?
        flash[:notice] = "No result found"
        @dogs = Dog.all
      end
    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dogs_path, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :owner_id, :breed_id, :dob, :allergies, :vet_name, :vet_phone, :in_daycare, :avatar)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin_user!, except: [:index, :show]
  
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  def index
    if params[:ownersearch]
      @owners = Owner.where("last_name LIKE ?", "%#{params[:ownersearch]}%")
      if @owners.size.zero?
        flash[:notice] = "No result found"
        @owners = Owner.all
      end
    else
      @owners = Owner.all
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:last_name, :first_name, :phone, :emergency_name, :emergency_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
</div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "ex. spot" %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, Owner.all, :id, :lastfirst, {prompt: "Select an owner"}, {class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :breed_id %><br>
    <%= f.collection_select :breed_id, Breed.all, :id, :breed, {prompt: "Select a breed"}, {class: "form-control"} %>
  </div>
  <div class="field">
    <%# TODO: CHANGE TO A DATEPICKER ONCE WE LEARN THAT LATER %>
    <%= f.label "Date of Birth" %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :allergies %><br>
    <%= f.text_field :allergies, class: "form-control", placeholder: "chocolate" %>
  </div>
  <div class="field">
    <%= f.label :vet_name %><br>
    <%= f.text_field :vet_name, class: "form-control", placeholder: "Dr. Doolittle" %>
  </div>
  <div class="field">
    <%= f.label :vet_phone %><br>
    <%= f.text_field :vet_phone, class: "form-control", placeholder: "555-555-5555" %>
  </div>
  <div class="field">
    <%= f.label :in_daycare %><br>
    <%= f.check_box :in_daycare %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Our Dogs</h1>

<div class="row">
  <%  @dogs.each do |dog| %>
    <div class="col-md-4">
       <div class="panel panel-default <%= 'panel-success' if dog.in_daycare %>">
         <div class="panel-heading">
           <h3 class="panel-title"><%= dog.name %> <%= dog.try(:owner).try(:last_name) %></h3>
         </div>
         <div class="panel-body">
           <%= form_for(dog, url: dog_path(dog), :html => {class: "form-inline"}) do |f| %>
            <% if dog.in_daycare %>
              <%= f.hidden_field :in_daycare, :value => false %>
              <%= f.submit "Check Out", class: "btn btn-warning btn-xs" %>
            <% else %>
              <%= f.hidden_field :in_daycare, :value => true %>
              <%= f.submit "Check In", class: "btn btn-success btn-xs" %>
            <% end %>
          <% end %>

  


           <%= image_tag dog.avatar.url(:medium), class: "img-responsive" %>
           <%= link_to fa_icon("eye", text: 'Show'), dog, class: "btn btn-primary btn-xs" %>
           <%= link_to fa_icon("pencil", text: 'Edit'), edit_dog_path(dog), class: "btn btn-warning btn-xs" %>
           <%= link_to fa_icon("trash-o", text: 'Delete'), dog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
         </div>
     </div>
   </div>
 <% end %>
</div>
      
<%= link_to 'New Dog', new_dog_path, class: "btn btn-success" %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @dog.name + " " + @dog.owner.last_name %>
</p>


<p>
  <strong>Owner:</strong>
  <%= @dog.owner.first_name + " " + @dog.owner.last_name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob.stamp("March 7, 1990") %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @dog.allergies %>
</p>

<p>
  <strong>Vet name:</strong>
  <%= @dog.vet_name %>
</p>

<p>
  <strong>Vet phone:</strong>
  <%= @dog.vet_phone %>
</p>

<p>
  <strong>In daycare:</strong>
  <%= @dog.in_daycare %>
</p>

<p>
 <%= image_tag @dog.avatar.url(:medium) %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog), class: "btn btn-primary" %> 
<%= link_to 'Back', dogs_path, class: "btn btn-default" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to fa_icon("fa fa-paw") , root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Owners", owners_url %></li>
        <li><%= link_to "Dogs", dogs_url %></li>
        <li><%= link_to "About", pages_about_url %></li>
      </ul>

      <%= form_tag("/dogs", method: "get", role: "search",
        class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:search, nil, placeholder: "Mittens", class: "form-control input-sm") %>
        </div>
        <%= submit_tag("Search", class: "btn btn-primary btn-sm") %>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
         <li class="welcome">Welcome <%= current_user.email %></li>
         <li><%= link_to fa_icon('cog', text: "Account"), edit_user_registration_path %></li>
         <li><%= link_to fa_icon('sign-out', text: 'Logout'), destroy_user_session_path, :method => :delete %></li>
       <% else %>
         <li><%= link_to fa_icon('check-circle-o', text: 'Sign Up'), new_user_registration_path %></li>
         <li><%= link_to fa_icon('sign-in', text: "Login"), new_user_session_path %></li>
       <% end %>
     </ul>

    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DoggyDaycare</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cosmo/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
      <% elsif alert.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control", placeholder: "Joe" %>
  </div>
  <div class="field form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Doe" %>
  </div>
  <div class="field form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "555-555-5555" %>
  </div>
  <div class="field form-group">
    <%= f.label :emergency_name %><br>
    <%= f.text_field :emergency_name, class: "form-control", placeholder: "Jane Doe" %>
  </div>
  <div class="field form-group">
    <%= f.label :emergency_phone %><br>
    <%= f.text_field :emergency_phone, class: "form-control", placeholder: "555-555-5554" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing Owners</h1>

 <%= form_tag("/owners", method: "get", role: "search",
        class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:ownersearch, nil, placeholder: "Joe", class: "form-control input-sm") %>
        </div>
        <%= submit_tag("Search", class: "btn btn-primary btn-sm") %>
      <% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone</th>
      <th>Emergency name</th>
      <th>Emergency phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.last_name %></td>
        <td><%= owner.first_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.emergency_name %></td>
        <td><%= owner.emergency_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path, class: "btn btn-success" %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Emergency name:</strong>
  <%= @owner.emergency_name %>
</p>

<p>
  <strong>Emergency phone:</strong>
  <%= @owner.emergency_phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container-fluid">
        <h1>Wuff Riders Daycare</h1>
    </div>
</div>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container-fluid">
      <h1>Wuff Riders Daycare</h1>
  </div>
</div>

<div class="container-fluid">
    <div class="row">
      <div class="col-md-12 text-center mission">
        <p>Here at Wuff Riders Daycare. 
        </p>
        <p><a class="btn btn-default" href="#" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Learn more!</a></p>
      </div>
    </div>